/* Generated by GOB (v2.0.14)   (do not edit directly) */


/* gcompris - gc-sound-mixer.gob
 *
 * Copyright (C) 2006 Yves Combe
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#line 1 "gc-sound-mixer-SDL.gob"
#line 25 "gc-sound-mixer-private.h"
#ifndef __GC_SOUND_MIXER_PRIVATE_H__
#define __GC_SOUND_MIXER_PRIVATE_H__

#include "gc-sound-mixer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct _GcSoundMixerPrivate {
#line 52 "gc-sound-mixer-SDL.gob"
	int audio_buffers;
#line 53 "gc-sound-mixer-SDL.gob"
	int bits;
#line 55 "gc-sound-mixer-SDL.gob"
	GList * channels_list;
#line 65 "gc-sound-mixer-SDL.gob"
	gboolean audio_device;
#line 108 "gc-sound-mixer-SDL.gob"
	gboolean sdl_ok;
#line 46 "gc-sound-mixer-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
